../../../librsvg/target/debug/rsvg-convert.exe -w 1024 -h 1024 -i "#heart_1" cards.svg -o heart_1.png
../../../librsvg/target/debug/rsvg-convert.exe -w 1024 -h 1024 -i "#heart_2" cards.svg -o heart_2.png
../../../librsvg/target/debug/rsvg-convert.exe -w 1024 -h 1024 -i "#heart_3" cards.svg -o heart_3.png
../../../librsvg/target/debug/rsvg-convert.exe -w 1024 -h 1024 -i "#heart_4" cards.svg -o heart_4.png
../../../librsvg/target/debug/rsvg-convert.exe -w 1024 -h 1024 -i "#heart_5" cards.svg -o heart_5.png
../../../librsvg/target/debug/rsvg-convert.exe -w 1024 -h 1024 -i "#heart_6" cards.svg -o heart_6.png
../../../librsvg/target/debug/rsvg-convert.exe -w 1024 -h 1024 -i "#heart_7" cards.svg -o heart_7.png
../../../librsvg/target/debug/rsvg-convert.exe -w 1024 -h 1024 -i "#heart_8" cards.svg -o heart_8.png
../../../librsvg/target/debug/rsvg-convert.exe -w 1024 -h 1024 -i "#heart_9" cards.svg -o heart_9.png
../../../librsvg/target/debug/rsvg-convert.exe -w 1024 -h 1024 -i "#heart_10" cards.svg -o heart_10.png
../../../librsvg/target/debug/rsvg-convert.exe -w 1024 -h 1024 -i "#heart_jack" cards.svg -o heart_knight.png
../../../librsvg/target/debug/rsvg-convert.exe -w 1024 -h 1024 -i "#heart_queen" cards.svg -o heart_queen.png
../../../librsvg/target/debug/rsvg-convert.exe -w 1024 -h 1024 -i "#heart_king" cards.svg -o heart_king.png
